require:
  - rubocop-rails
  - rubocop-performance

AllCops:
  NewCops: disable
  Exclude:
    - bin/*

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/AsciiComments:
  Enabled: false
