version: 2
jobs:
  build:
    parallelism: 1
    docker:
      - image: circleci/ruby:3.0.1
        environment:
          BUNDLE_JOBS: 3
          BUNDLE_RETRY: 3
          BUNDLE_PATH: vendor/bundle
          PGHOST: 127.0.0.1
          PGUSER: root
          RAILS_ENV: test
      - image: circleci/postgres
        environment:
          POSTGRES_USER: root
          POSTGRES_HOST_AUTH_METHOD: trust
    steps:
      - checkout

      - run:
          name: Bundler の指定
          command: bundle -v

      - restore_cache:
          keys:
            - rails-demo-bundle-v2-{{ checksum "Gemfile.lock" }}
            - rails-demo-bundle-v2-

      - run:
          name: bundle install
          command: bundle config set --local path 'vendor/bundle' || bundle check --path || bundle install --deployment

      - save_cache:
          key: rails-demo-bundle-v2-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle

      - run:
          name: 静的解析の実行
          command: bundle exec rubocop -c .rubocop.yml

      - run:
          name: DB の待機
          command: dockerize -wait tcp://localhost:5432 -timeout 1m

      - run:
          name: データベースのセットアップ
          command: bin/rails db:setup --trace

      - run:
          name: テストの実行
          command: bin/rails t

      - store_artifacts:
          path: coverage
